import { defineExercise } from '../define';

export const armExercises = [
  // --- Biceps -------------------------------------------------------------
  defineExercise({
    slug: 'barbell-curl',
    name: 'Barbell Curl',
    description: 'The classic straight-bar curl for overall biceps mass.',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['barbell', 'ez_bar'],
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Stand holding the bar at shoulder width, elbows at your sides.',
      'Curl the bar up without moving the upper arms.',
      'Lower all the way to straight arms.',
    ],
    commonMistakes: ['Swinging the hips.', 'Cutting the bottom half of the rep.', 'Elbows drifting forward into a front raise.'],
    scienceExplanation:
      'Bilateral barbell loading lets you progress the biceps in small precise steps across a full range.',
    progressionInstructions: 'Add the smallest increment after topping the rep range on all sets.',
    equivalentAlternatives: ['dumbbell-curl', 'ez-bar-curl', 'cable-curl'],
  }),
  defineExercise({
    slug: 'ez-bar-curl',
    name: 'EZ-Bar Curl',
    description: 'Curl with a cambered bar for a wrist-friendly grip angle.',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['ez_bar'],
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Grip the angled sections of the bar.',
      'Curl with pinned elbows; lower fully.',
    ],
    commonMistakes: ['Leaning back to finish reps.'],
    scienceExplanation:
      'The semi-supinated grip reduces wrist strain while keeping nearly all of the biceps stimulus of a straight bar.',
    progressionInstructions: 'Smallest plate increments once the rep range tops out.',
    equivalentAlternatives: ['barbell-curl', 'dumbbell-curl'],
  }),
  defineExercise({
    slug: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    description: 'Alternating or simultaneous dumbbell curls with full supination.',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell', 'adjustable_dumbbell'],
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Stand with dumbbells at your sides, palms in.',
      'Curl while rotating the palm up.',
      'Lower fully with control.',
    ],
    commonMistakes: ['Swinging.', 'Half-range reps.'],
    scienceExplanation:
      'Independent arms plus active supination train both elbow flexion functions of the biceps.',
    progressionInstructions: 'Dumbbell steps are big relative to biceps strength — earn extra reps first.',
    equivalentAlternatives: ['barbell-curl', 'cable-curl', 'hammer-curl'],
  }),
  defineExercise({
    slug: 'hammer-curl',
    name: 'Hammer Curl',
    description: 'Neutral-grip curl hitting the brachialis and forearms.',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell', 'adjustable_dumbbell'],
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Hold dumbbells with palms facing each other.',
      'Curl without rotating the wrist.',
      'Lower fully.',
    ],
    commonMistakes: ['Elbows drifting behind the body.'],
    scienceExplanation:
      'The neutral grip biases the brachialis, a deep elbow flexor that pushes the biceps up and adds arm thickness.',
    progressionInstructions: 'Reps to the top of the range, then a dumbbell step.',
    equivalentAlternatives: ['dumbbell-curl', 'cable-curl'],
  }),
  defineExercise({
    slug: 'incline-dumbbell-curl',
    name: 'Incline Dumbbell Curl',
    description: 'Curl lying back on an incline bench, arms hanging for a long-length stretch.',
    primaryMuscles: ['biceps'],
    equipment: ['dumbbell', 'incline_bench'],
    movementPattern: 'elbow_flexion',
    difficulty: 'intermediate',
    exerciseType: 'isolation',
    instructions: [
      'Set the bench to about 45–60° and lie back with arms hanging.',
      'Curl without letting the elbows travel forward.',
      'Lower to a full stretch behind your body line.',
    ],
    commonMistakes: ['Elbows swinging forward.', 'Shortening the negative.'],
    scienceExplanation:
      'Puts the long head of the biceps under stretch during loading — training at long lengths is a potent growth signal.',
    progressionInstructions: 'Progress reps first; this position is unforgiving with heavy jumps.',
    equivalentAlternatives: ['dumbbell-curl', 'cable-curl'],
  }),
  defineExercise({
    slug: 'cable-curl',
    name: 'Cable Curl',
    description: 'Low-pulley curl with tension through the whole arc.',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['cable_machine'],
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Attach a bar or rope to the low pulley.',
      'Curl with elbows pinned, lower fully against the cable.',
    ],
    commonMistakes: ['Stepping so close the bottom loses tension.'],
    scienceExplanation:
      'The cable keeps resistance on the biceps at the bottom and top, unlike free weights which unload at both ends.',
    progressionInstructions: 'Small stack pins after topping the range.',
    equivalentAlternatives: ['barbell-curl', 'dumbbell-curl'],
  }),
  defineExercise({
    slug: 'band-curl',
    name: 'Resistance Band Curl',
    description: 'Band curl for biceps work with minimal equipment.',
    primaryMuscles: ['biceps'],
    equipment: ['resistance_band'],
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: ['Stand on the band, curl the handles with pinned elbows, lower slowly.'],
    commonMistakes: ['Letting the band yank the arms down.'],
    scienceExplanation:
      'Bands make curls loadable anywhere; the slow negative against band recoil adds effective tension.',
    progressionInstructions: 'Add reps, widen stance, or thicken the band.',
    equivalentAlternatives: ['dumbbell-curl'],
  }),
  defineExercise({
    slug: 'preacher-curl',
    name: 'Preacher Curl',
    description: 'Curl braced on a preacher pad, eliminating body momentum.',
    primaryMuscles: ['biceps'],
    equipment: ['ez_bar', 'dumbbell', 'selectorized_machine'],
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Rest the backs of your upper arms on the pad.',
      'Curl up, then lower until arms are nearly straight.',
    ],
    commonMistakes: ['Lifting the elbows off the pad.', 'Bouncing at the stretched bottom.'],
    scienceExplanation:
      'The pad blocks cheating and loads the biceps hard in the stretched half of the rep — the most growth-relevant part.',
    progressionInstructions: 'Small increments; never sacrifice the full lowering phase.',
    equivalentAlternatives: ['incline-dumbbell-curl', 'cable-curl'],
  }),
  // --- Triceps ------------------------------------------------------------
  defineExercise({
    slug: 'triceps-pushdown',
    name: 'Cable Triceps Pushdown',
    description: 'The staple cable extension for all three triceps heads.',
    primaryMuscles: ['triceps'],
    equipment: ['cable_machine'],
    movementPattern: 'elbow_extension',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Grab a bar or rope at a high pulley, elbows pinned to your sides.',
      'Extend until your arms are straight.',
      'Return to about 90° or slightly above without moving the elbows.',
    ],
    commonMistakes: ['Leaning over the weight and pressing with bodyweight.', 'Elbows flaring out.'],
    scienceExplanation:
      'Easy to load precisely and easy on the elbows — a dependable triceps volume driver behind your pressing.',
    progressionInstructions: 'One pin at a time once all sets top the range.',
    equivalentAlternatives: ['overhead-triceps-extension', 'band-pushdown'],
  }),
  defineExercise({
    slug: 'overhead-triceps-extension',
    name: 'Overhead Triceps Extension',
    description: 'Cable or dumbbell extension overhead, stretching the long head.',
    primaryMuscles: ['triceps'],
    equipment: ['cable_machine', 'dumbbell'],
    movementPattern: 'elbow_extension',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Hold a rope or single dumbbell overhead, elbows close to your head.',
      'Lower behind your head until you feel a deep triceps stretch.',
      'Extend back to straight arms.',
    ],
    commonMistakes: ['Elbows drifting wide.', 'Arching the lower back.'],
    scienceExplanation:
      'The overhead position stretches the long head of the triceps, and stretched-position training produces more growth than the same work done at short lengths.',
    progressionInstructions: 'Small increments; keep the stretch honest.',
    equivalentAlternatives: ['triceps-pushdown', 'skull-crusher'],
  }),
  defineExercise({
    slug: 'skull-crusher',
    name: 'Lying Triceps Extension',
    aliases: ['Skull Crusher'],
    description: 'Lying EZ-bar extension lowering to the forehead or behind the head.',
    primaryMuscles: ['triceps'],
    equipment: ['ez_bar', 'bench', 'dumbbell'],
    movementPattern: 'elbow_extension',
    difficulty: 'intermediate',
    exerciseType: 'isolation',
    instructions: [
      'Lie on a bench holding an EZ-bar over your chest.',
      'Bend only at the elbows, lowering the bar to your forehead or just behind the head.',
      'Extend back to the start.',
    ],
    commonMistakes: ['Flaring the elbows.', 'Turning it into a close-grip press.'],
    scienceExplanation:
      'Loads the triceps heavily through a long range; lowering slightly behind the head adds long-head stretch.',
    progressionInstructions: 'Smallest bar increments after topping the range on all sets.',
    easierAlternatives: ['triceps-pushdown'],
    equivalentAlternatives: ['overhead-triceps-extension'],
  }),
  defineExercise({
    slug: 'close-grip-bench-press',
    name: 'Close-Grip Bench Press',
    description: 'Narrow-grip barbell press shifting emphasis to the triceps.',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: ['barbell', 'bench', 'squat_rack'],
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    instructions: [
      'Grip the bar at about shoulder width.',
      'Lower to the lower chest with elbows tucked.',
      'Press to lockout, focusing on the triceps finishing the rep.',
    ],
    commonMistakes: ['Grip so narrow the wrists hurt.', 'Elbows flaring wide.'],
    scienceExplanation:
      'Lets the triceps be trained with compound-level loads — heavier tension than isolation work can provide.',
    progressionInstructions: 'Standard double progression with the smallest plate steps.',
    equivalentAlternatives: ['triceps-dip', 'skull-crusher'],
  }),
  defineExercise({
    slug: 'triceps-dip',
    name: 'Triceps Dip',
    description: 'Upright dip keeping the torso vertical to bias the triceps.',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: ['dip_station'],
    movementPattern: 'elbow_extension',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    trackingType: 'weighted_bodyweight',
    instructions: [
      'Support on parallel bars with an upright torso.',
      'Lower until elbows reach about 90°.',
      'Press back to straight arms.',
    ],
    commonMistakes: ['Excessive depth with tight shoulders.', 'Leaning far forward (shifts to chest).'],
    scienceExplanation:
      'Compound bodyweight triceps loading, easily progressed with a dip belt.',
    progressionInstructions: 'Reps to the top of the range, then add belt weight.',
    easierAlternatives: ['bench-dip', 'triceps-pushdown'],
    equivalentAlternatives: ['close-grip-bench-press'],
  }),
  defineExercise({
    slug: 'bench-dip',
    name: 'Bench Dip',
    description: 'Feet-on-floor dip off a bench — an accessible triceps builder.',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['shoulders'],
    equipment: ['bench', 'bodyweight'],
    movementPattern: 'elbow_extension',
    difficulty: 'beginner',
    exerciseType: 'compound',
    trackingType: 'bodyweight_reps',
    instructions: [
      'Hands on a bench behind you, legs extended forward.',
      'Lower until elbows reach ~90°, then press up.',
    ],
    commonMistakes: ['Shoulders rolling forward at the bottom.', 'Hips drifting far from the bench.'],
    scienceExplanation:
      'Scales triceps pressing to beginners; foot elevation and added plates keep it progressing.',
    progressionInstructions: 'Add reps, elevate the feet, then add a plate on the lap.',
    harderAlternatives: ['triceps-dip'],
    equivalentAlternatives: ['triceps-pushdown'],
  }),
  defineExercise({
    slug: 'band-pushdown',
    name: 'Band Triceps Pushdown',
    description: 'Pushdown against a band anchored overhead.',
    primaryMuscles: ['triceps'],
    equipment: ['resistance_band'],
    movementPattern: 'elbow_extension',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Anchor a band overhead, elbows pinned at your sides.',
      'Extend to straight arms, return with control.',
    ],
    commonMistakes: ['Elbows rising as you extend.'],
    scienceExplanation:
      'Band tension peaks at lockout where the triceps finish the rep — a reasonable match for the strength curve.',
    progressionInstructions: 'Add reps or use a thicker band.',
    equivalentAlternatives: ['triceps-pushdown'],
  }),
  defineExercise({
    slug: 'diamond-push-up',
    name: 'Diamond Push-Up',
    description: 'Close-hand push-up loading the triceps hard.',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: ['bodyweight'],
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    trackingType: 'bodyweight_reps',
    instructions: [
      'Form a diamond with thumbs and index fingers under your chest.',
      'Lower with elbows tucked, press back up.',
    ],
    commonMistakes: ['Elbows flaring.', 'Sagging hips.'],
    scienceExplanation:
      'The narrow hand position increases elbow-extension demand, turning a push-up into triceps-dominant work.',
    progressionInstructions: 'Add reps, then elevate feet or add load.',
    easierAlternatives: ['push-up'],
    equivalentAlternatives: ['bench-dip'],
  }),
] as const;
