import { defineExercise } from '../define';

export const backExercises = [
  defineExercise({
    slug: 'pull-up',
    name: 'Pull-Up',
    description: 'Overhand-grip vertical pull, the benchmark upper-back and lat builder.',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['pull_up_bar'],
    movementPattern: 'vertical_pull',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    trackingType: 'weighted_bodyweight',
    instructions: [
      'Hang from the bar with an overhand grip slightly wider than shoulders.',
      'Pull your chest toward the bar, leading with the elbows.',
      'Lower under control to a full hang.',
    ],
    commonMistakes: ['Kipping or swinging.', 'Half-range reps that skip the dead hang.', 'Shrugging instead of depressing the shoulder blades.'],
    scienceExplanation:
      'Vertical pulling trains the lats through a long range under bodyweight-scale load — easily progressed with added weight.',
    progressionInstructions:
      'Add reps until the top of the range, then add small amounts of weight on a belt and rebuild.',
    easierAlternatives: ['lat-pulldown', 'band-assisted-pull-up'],
    harderAlternatives: [],
    equivalentAlternatives: ['chin-up', 'lat-pulldown'],
  }),
  defineExercise({
    slug: 'chin-up',
    name: 'Chin-Up',
    description: 'Underhand-grip pull-up with extra biceps involvement.',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['pull_up_bar'],
    movementPattern: 'vertical_pull',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    trackingType: 'weighted_bodyweight',
    instructions: [
      'Hang with an underhand, shoulder-width grip.',
      'Pull until your chin clears the bar.',
      'Lower to a controlled dead hang.',
    ],
    commonMistakes: ['Cutting the bottom range.', 'Excessive swinging.'],
    scienceExplanation:
      'The supinated grip lets the biceps contribute strongly, making it both a lat and arm builder.',
    progressionInstructions: 'Same double progression as pull-ups: reps first, then added load.',
    easierAlternatives: ['lat-pulldown', 'band-assisted-pull-up'],
    equivalentAlternatives: ['pull-up', 'lat-pulldown'],
  }),
  defineExercise({
    slug: 'band-assisted-pull-up',
    name: 'Band-Assisted Pull-Up',
    description: 'Pull-up with band assistance to work full range before unassisted reps arrive.',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['pull_up_bar', 'resistance_band'],
    movementPattern: 'vertical_pull',
    difficulty: 'beginner',
    exerciseType: 'compound',
    trackingType: 'bodyweight_reps',
    instructions: [
      'Loop a band over the bar and place one knee or foot in it.',
      'Perform strict full-range pull-ups.',
    ],
    commonMistakes: ['Using a band so thick the top of the rep takes no effort.'],
    scienceExplanation:
      'Bands assist most at the bottom where you are weakest, letting you accumulate quality full-range vertical pulling volume.',
    progressionInstructions: 'Move to progressively thinner bands, then unassisted reps.',
    harderAlternatives: ['pull-up', 'chin-up'],
    equivalentAlternatives: ['lat-pulldown'],
  }),
  defineExercise({
    slug: 'lat-pulldown',
    name: 'Lat Pulldown',
    description: 'Cable vertical pull with precise load selection for lat development.',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['cable_machine', 'selectorized_machine'],
    movementPattern: 'vertical_pull',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: [
      'Sit with thighs secured, grip the bar slightly wider than shoulders.',
      'Pull the bar to the upper chest, driving elbows down and back.',
      'Let the bar rise until arms are long and lats stretch.',
    ],
    commonMistakes: ['Leaning way back and rowing the weight.', 'Pulling behind the neck.', 'Half-range reps at the top.'],
    scienceExplanation:
      'Delivers the same vertical-pull stimulus as pull-ups with fine-grained load control, ideal for staying in the target rep range.',
    progressionInstructions: 'One stack pin at a time once all sets top the range at target RIR.',
    harderAlternatives: ['pull-up', 'chin-up'],
    equivalentAlternatives: ['pull-up'],
  }),
  defineExercise({
    slug: 'barbell-row',
    name: 'Barbell Row',
    aliases: ['Bent-Over Row'],
    description: 'Hip-hinged barbell row for mid-back thickness and lat mass.',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'lower_back', 'forearms'],
    equipment: ['barbell'],
    movementPattern: 'horizontal_pull',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    instructions: [
      'Hinge to roughly 45° or lower with a flat back, bar hanging at arm length.',
      'Row the bar to your lower ribs, elbows tracking close.',
      'Lower under control without losing the hinge.',
    ],
    commonMistakes: ['Standing up as reps get hard.', 'Yanking with momentum.', 'Rounding the lower back.'],
    scienceExplanation:
      'A heavy horizontal pull hitting lats, rhomboids, and traps together; the hinge position also builds isometric lower-back strength.',
    progressionInstructions: 'Add the smallest plate increment after topping the rep range on all sets.',
    easierAlternatives: ['chest-supported-row', 'seated-cable-row'],
    equivalentAlternatives: ['dumbbell-row', 'chest-supported-row'],
  }),
  defineExercise({
    slug: 'dumbbell-row',
    name: 'One-Arm Dumbbell Row',
    description: 'Bench-supported single-arm row with a big stretch and strict control.',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['dumbbell', 'bench'],
    movementPattern: 'horizontal_pull',
    difficulty: 'beginner',
    exerciseType: 'compound',
    laterality: 'unilateral',
    instructions: [
      'Place one knee and hand on a bench, back flat.',
      'Let the dumbbell hang and stretch the lat.',
      'Row to your hip, then lower with control.',
    ],
    commonMistakes: ['Rotating the torso to heave the weight.', 'Rowing to the shoulder instead of the hip.'],
    scienceExplanation:
      'The support removes lower-back fatigue as a limiter, and unilateral work lets each side get a full stretch and contraction.',
    progressionInstructions: 'Move up one dumbbell step when both arms top the rep range.',
    equivalentAlternatives: ['chest-supported-row', 'seated-cable-row'],
  }),
  defineExercise({
    slug: 'chest-supported-row',
    name: 'Chest-Supported Dumbbell Row',
    description: 'Row lying prone on an incline bench — pure back work, zero lower-back strain.',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'shoulders'],
    equipment: ['dumbbell', 'incline_bench'],
    movementPattern: 'horizontal_pull',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: [
      'Lie chest-down on a 30–45° incline bench holding dumbbells.',
      'Row the dumbbells to your hips, squeezing the shoulder blades.',
      'Lower to a full stretch each rep.',
    ],
    commonMistakes: ['Lifting the chest off the pad.', 'Short choppy reps.'],
    scienceExplanation:
      'Chest support isolates the upper back from cheating and spinal load, so every rep is productive rowing volume.',
    progressionInstructions: 'Dumbbell steps after topping the range on all sets.',
    equivalentAlternatives: ['seated-cable-row', 'machine-row', 'barbell-row'],
  }),
  defineExercise({
    slug: 'seated-cable-row',
    name: 'Seated Cable Row',
    description: 'Cable row with constant tension for mid-back and lats.',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['cable_machine'],
    movementPattern: 'horizontal_pull',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: [
      'Sit tall with knees soft, grab the handle.',
      'Pull to your stomach, driving elbows back.',
      'Let the handle travel forward until the lats stretch, keeping the torso mostly upright.',
    ],
    commonMistakes: ['Rocking the torso for momentum.', 'Shrugging into the shoulders.'],
    scienceExplanation:
      'Constant cable tension plus easy load adjustment makes this a reliable horizontal-pull volume driver.',
    progressionInstructions: 'One stack pin at a time after all sets top the range.',
    equivalentAlternatives: ['machine-row', 'chest-supported-row'],
  }),
  defineExercise({
    slug: 'machine-row',
    name: 'Machine Row',
    description: 'Plate-loaded or selectorized row with chest support.',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['plate_loaded_machine', 'selectorized_machine'],
    movementPattern: 'horizontal_pull',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: [
      'Adjust the seat so handles align with your mid-torso.',
      'Row with the chest against the pad, squeezing the blades together.',
      'Return to a full stretch.',
    ],
    commonMistakes: ['Pulling with arms only, no shoulder-blade movement.'],
    scienceExplanation:
      'Machine stability makes near-failure rowing safe, which matters because effective reps come near failure.',
    progressionInstructions: 'Smallest machine increment after topping the range.',
    equivalentAlternatives: ['seated-cable-row', 'chest-supported-row'],
  }),
  defineExercise({
    slug: 'inverted-row',
    name: 'Inverted Row',
    description: 'Bodyweight row under a bar — scalable horizontal pulling anywhere.',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'abs'],
    equipment: ['bodyweight', 'smith_machine', 'squat_rack'],
    movementPattern: 'horizontal_pull',
    difficulty: 'beginner',
    exerciseType: 'compound',
    trackingType: 'bodyweight_reps',
    instructions: [
      'Set a bar at waist height and hang beneath it, body straight.',
      'Pull your chest to the bar.',
      'Lower with control keeping hips in line.',
    ],
    commonMistakes: ['Hips sagging.', 'Partial reps at the top.'],
    scienceExplanation:
      'Body angle acts as the load dial: more horizontal is harder, letting you keep the movement in a growth-effective rep range.',
    progressionInstructions: 'Lower the bar or elevate your feet as reps exceed the target range.',
    harderAlternatives: ['barbell-row'],
    equivalentAlternatives: ['seated-cable-row'],
  }),
  defineExercise({
    slug: 'band-row',
    name: 'Resistance Band Row',
    description: 'Anchored band row for horizontal pulling with minimal equipment.',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['resistance_band'],
    movementPattern: 'horizontal_pull',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: [
      'Anchor the band at chest height and step back until taut.',
      'Row the handles to your ribs, squeezing the blades.',
      'Return slowly, resisting the band.',
    ],
    commonMistakes: ['Standing too close, losing tension at the stretch.'],
    scienceExplanation:
      'Bands provide accommodating resistance; standing farther away progressively raises the challenge.',
    progressionInstructions: 'Add reps, shorten the band, or move to a thicker band.',
    harderAlternatives: ['seated-cable-row', 'barbell-row'],
  }),
  defineExercise({
    slug: 'straight-arm-pulldown',
    name: 'Straight-Arm Pulldown',
    aliases: ['Cable Pullover'],
    description: 'Cable lat isolation sweeping the arms down with fixed elbows.',
    primaryMuscles: ['back'],
    secondaryMuscles: ['triceps'],
    equipment: ['cable_machine'],
    movementPattern: 'pullover',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Face a high pulley holding a bar or rope with nearly straight arms.',
      'Sweep your hands down to your thighs in an arc.',
      'Return until your arms are overhead and lats stretch.',
    ],
    commonMistakes: ['Bending the elbows into a pulldown.', 'Hunching the torso to move more weight.'],
    scienceExplanation:
      'Removes the biceps from the pull so the lats do all the shortening work — useful extra lat volume without grip fatigue.',
    progressionInstructions: 'Small stack increments; keep the arc long and strict.',
    equivalentAlternatives: ['dumbbell-pullover'],
  }),
  defineExercise({
    slug: 'dumbbell-pullover',
    name: 'Dumbbell Pullover',
    description: 'Lying pullover stretching lats and chest through a long overhead arc.',
    primaryMuscles: ['back'],
    secondaryMuscles: ['chest', 'triceps'],
    equipment: ['dumbbell', 'bench'],
    movementPattern: 'pullover',
    difficulty: 'intermediate',
    exerciseType: 'isolation',
    instructions: [
      'Lie across or along a bench holding one dumbbell over your chest.',
      'Lower it behind your head with slightly bent arms until you feel a deep stretch.',
      'Pull back over your chest.',
    ],
    commonMistakes: ['Bending the elbows more as the weight moves back.', 'Overarching the lower back.'],
    scienceExplanation:
      'Loads the lats at their most lengthened overhead position — a stretch stimulus vertical pulls only partially provide.',
    progressionInstructions: 'Add reps first, then small dumbbell steps.',
    equivalentAlternatives: ['straight-arm-pulldown'],
  }),
  defineExercise({
    slug: 'face-pull',
    name: 'Cable Face Pull',
    description: 'High-cable pull to the face for rear delts, mid-traps, and rotator cuff.',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back'],
    equipment: ['cable_machine'],
    movementPattern: 'rear_delt',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Set a rope at upper-chest height, grab with thumbs toward you.',
      'Pull the rope toward your face, spreading the ends and rotating knuckles back.',
      'Return slowly with control.',
    ],
    commonMistakes: ['Going heavy and turning it into a row.', 'No external rotation at the end.'],
    scienceExplanation:
      'Balances the heavy pressing in your program by strengthening the rear delts and scapular muscles that support shoulder health.',
    progressionInstructions: 'High reps, small stack jumps; chase quality over load.',
    equivalentAlternatives: ['reverse-fly', 'band-pull-apart'],
  }),
  defineExercise({
    slug: 'back-extension',
    name: 'Back Extension',
    aliases: ['Hyperextension'],
    description: 'Hip-hinge extension on a bench or floor for spinal erectors and glutes.',
    primaryMuscles: ['lower_back'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['bodyweight', 'plate_loaded_machine'],
    movementPattern: 'hip_hinge',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    trackingType: 'weighted_bodyweight',
    instructions: [
      'Set up on a 45° back-extension bench with hips just above the pad.',
      'Hinge down until your hamstrings stretch.',
      'Raise your torso to a straight line — no hyperextension.',
    ],
    commonMistakes: ['Hyperextending at the top.', 'Bouncing at the bottom.'],
    scienceExplanation:
      'Builds the erectors and glutes that stabilize rows, squats, and hinges, raising how much productive heavy work you can tolerate.',
    progressionInstructions: 'Add reps, then hold a plate to your chest.',
    equivalentAlternatives: ['romanian-deadlift'],
  }),
] as const;
