import { defineExercise } from '../define';

export const calfCoreExercises = [
  defineExercise({
    slug: 'machine-crunch',
    name: 'Abdominal Crunch Machine',
    aliases: ['Crunch Machine', 'Machine Crunch'],
    description: 'Loaded machine crunch for measurable spinal-flexion progression.',
    primaryMuscles: ['abs'],
    equipment: ['selectorized_machine'],
    movementPattern: 'ab_flexion',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Set the pivot to match the torso.',
      'Curl the ribs toward the pelvis.',
      'Return under control without letting the stack slam.',
    ],
    commonMistakes: ['Pulling with the arms.', 'Hinging only at the hips.'],
    scienceExplanation:
      'Stable machine resistance lets the abs be trained and progressed like any other muscle.',
    progressionInstructions: 'Add the smallest stack increment after both sets improve.',
    equivalentAlternatives: ['cable-crunch', 'weighted-crunch'],
  }),
  defineExercise({
    slug: 'machine-oblique-crunch',
    name: 'Machine Oblique Crunch',
    aliases: ['Oblique Crunch Machine', 'Side Machine Crunch'],
    description: 'Side-facing crunch on an abdominal machine to bias the obliques.',
    primaryMuscles: ['abs'],
    equipment: ['selectorized_machine'],
    movementPattern: 'ab_flexion',
    difficulty: 'intermediate',
    exerciseType: 'isolation',
    laterality: 'unilateral',
    instructions: [
      'Sit side-on and secure the torso against the pad.',
      'Crunch the ribs toward the same-side hip.',
      'Complete equal controlled sets on both sides.',
    ],
    commonMistakes: ['Rotating through the hips.', 'Training one side through a shorter range.'],
    scienceExplanation:
      'The side-on setup progressively loads lateral trunk flexion while keeping resistance measurable.',
    progressionInstructions: 'Match repetitions and range on both sides before adding weight.',
    equivalentAlternatives: ['pallof-press'],
  }),
  defineExercise({
    slug: 'dragon-flag',
    name: 'Dragon Flag',
    description: 'Advanced bodyweight anti-extension movement using the shoulders as the anchor.',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['back'],
    equipment: ['bench', 'bodyweight'],
    movementPattern: 'anti_extension',
    difficulty: 'advanced',
    exerciseType: 'compound',
    trackingType: 'bodyweight_reps',
    instructions: [
      'Grip the bench behind the head and raise the body as one rigid line.',
      'Lower from the shoulders without folding at the hips.',
      'Stop before the lower back loses control.',
    ],
    commonMistakes: ['Bending at the hips.', 'Dropping through the eccentric.'],
    scienceExplanation:
      'The long lever creates very high anti-extension demand across the rectus abdominis.',
    progressionInstructions: 'Build controlled negatives, then increase full-range repetitions.',
    easierAlternatives: ['reverse-crunch', 'hanging-leg-raise'],
  }),
  defineExercise({
    slug: 'incline-treadmill-walk',
    name: 'Incline Treadmill Walk',
    aliases: ['Treadmill Incline Walk', 'Incline Walking'],
    description: 'Timed treadmill walking at a controlled speed and incline.',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['glutes', 'hamstrings', 'quadriceps'],
    equipment: ['bodyweight'],
    movementPattern: 'cardio',
    difficulty: 'beginner',
    exerciseType: 'compound',
    trackingType: 'time',
    instructions: [
      'Set the programmed incline and speed.',
      'Walk without hanging from the handrails.',
      'Keep a steady sustainable stride for the full interval.',
    ],
    commonMistakes: ['Supporting bodyweight on the rails.', 'Shortening the stride excessively.'],
    scienceExplanation:
      'Incline walking raises cardiovascular demand with low impact while loading the posterior chain more than level walking.',
    progressionInstructions: 'Increase duration first, then incline or speed in small steps.',
  }),
  // --- Calves -------------------------------------------------------------
  defineExercise({
    slug: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    description: 'Straight-knee calf raise for the gastrocnemius.',
    primaryMuscles: ['calves'],
    equipment: ['selectorized_machine', 'smith_machine', 'dumbbell', 'bodyweight'],
    movementPattern: 'calf_raise',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Stand with the balls of your feet on an edge, heels hanging.',
      'Lower into a deep stretch and pause briefly.',
      'Rise to full tip-toe and squeeze.',
    ],
    commonMistakes: ['Bouncing out of the stretch.', 'Half-range pulsing.'],
    scienceExplanation:
      'The paused deep stretch matters most — calves respond strongly to loaded stretch, and bouncing robs that stimulus.',
    progressionInstructions: 'Add load in small steps; keep a 1–2 s pause at the bottom.',
    equivalentAlternatives: ['single-leg-calf-raise', 'leg-press-calf-raise'],
  }),
  defineExercise({
    slug: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    description: 'Bent-knee raise biasing the soleus.',
    primaryMuscles: ['calves'],
    equipment: ['plate_loaded_machine', 'selectorized_machine', 'dumbbell'],
    movementPattern: 'calf_raise',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Sit with the pad on your knees, balls of feet on the platform.',
      'Lower to a full stretch, rise to full contraction.',
    ],
    commonMistakes: ['Fast bouncy reps.'],
    scienceExplanation:
      'With bent knees the gastrocnemius slackens, so the deeper soleus does the work — together they build complete calf size.',
    progressionInstructions: 'Small plate steps; pause the stretch.',
    equivalentAlternatives: ['standing-calf-raise'],
  }),
  defineExercise({
    slug: 'single-leg-calf-raise',
    name: 'Single-Leg Calf Raise',
    description: 'Bodyweight calf raise one leg at a time — no machine needed.',
    primaryMuscles: ['calves'],
    equipment: ['bodyweight', 'dumbbell'],
    movementPattern: 'calf_raise',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    laterality: 'unilateral',
    trackingType: 'weighted_bodyweight',
    instructions: [
      'Stand on one foot on a step, holding support.',
      'Lower to a deep stretch, rise to full height.',
    ],
    commonMistakes: ['Using the support hand to pull yourself up.'],
    scienceExplanation:
      'Bodyweight on one leg is usually enough load to keep calves in an effective rep range for a long time.',
    progressionInstructions: 'Add reps, then hold a dumbbell.',
    equivalentAlternatives: ['standing-calf-raise'],
  }),
  defineExercise({
    slug: 'leg-press-calf-raise',
    name: 'Leg Press Calf Raise',
    description: 'Calf pressing on the leg-press sled with precise loading.',
    primaryMuscles: ['calves'],
    equipment: ['leg_press'],
    movementPattern: 'calf_raise',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Place the balls of your feet at the platform edge.',
      'Let the sled stretch your calves fully, then press to full extension of the ankles.',
    ],
    commonMistakes: ['Unlocking the knees to leg-press the weight.'],
    scienceExplanation:
      'Uses the leg press to load the calf stretch heavily with easy weight adjustments.',
    progressionInstructions: 'Small plate steps with a paused stretch.',
    equivalentAlternatives: ['standing-calf-raise', 'seated-calf-raise'],
  }),
  // --- Abs / core ---------------------------------------------------------
  defineExercise({
    slug: 'cable-crunch',
    name: 'Cable Crunch',
    description: 'Kneeling weighted crunch with progressive loading for the abs.',
    primaryMuscles: ['abs'],
    equipment: ['cable_machine'],
    movementPattern: 'ab_flexion',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Kneel below a rope attachment held beside your head.',
      'Crunch your ribs toward your pelvis, rounding the spine.',
      'Return until the abs stretch.',
    ],
    commonMistakes: ['Hinging at the hips instead of flexing the spine.', 'Pulling with the arms.'],
    scienceExplanation:
      'Abs grow like any muscle — with progressive load. Cable crunches make ab loading measurable and progressable.',
    progressionInstructions: 'One pin at a time within the rep range.',
    equivalentAlternatives: ['weighted-crunch', 'hanging-knee-raise'],
  }),
  defineExercise({
    slug: 'weighted-crunch',
    name: 'Weighted Crunch',
    description: 'Floor crunch holding a plate or dumbbell for resistance.',
    primaryMuscles: ['abs'],
    equipment: ['bodyweight', 'dumbbell'],
    movementPattern: 'ab_flexion',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    trackingType: 'weighted_bodyweight',
    instructions: [
      'Lie with knees bent, plate held on your chest or at arm’s length.',
      'Curl your ribs toward your pelvis.',
      'Lower slowly.',
    ],
    commonMistakes: ['Yanking the neck.', 'Sitting all the way up with hip flexors.'],
    scienceExplanation:
      'Short-range spinal flexion under load targets the rectus abdominis directly.',
    progressionInstructions: 'Add reps, then hold heavier weight.',
    equivalentAlternatives: ['cable-crunch'],
  }),
  defineExercise({
    slug: 'hanging-knee-raise',
    name: 'Hanging Knee Raise',
    description: 'Hanging from a bar, curling the knees and pelvis up.',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['forearms'],
    equipment: ['pull_up_bar'],
    movementPattern: 'ab_flexion',
    difficulty: 'intermediate',
    exerciseType: 'isolation',
    trackingType: 'bodyweight_reps',
    instructions: [
      'Hang from a bar with straight arms.',
      'Curl your knees up and roll the pelvis toward your ribs.',
      'Lower slowly without swinging.',
    ],
    commonMistakes: ['Swinging for momentum.', 'Lifting knees without tilting the pelvis.'],
    scienceExplanation:
      'Trains the lower fibers of the abs through pelvic tilt while building grip endurance.',
    progressionInstructions: 'Straighten the legs over time toward toes-to-bar.',
    easierAlternatives: ['reverse-crunch'],
    harderAlternatives: ['hanging-leg-raise'],
  }),
  defineExercise({
    slug: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    description: 'Straight-leg raise to horizontal or above.',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['forearms'],
    equipment: ['pull_up_bar'],
    movementPattern: 'ab_flexion',
    difficulty: 'advanced',
    exerciseType: 'isolation',
    trackingType: 'bodyweight_reps',
    instructions: [
      'Hang with straight legs.',
      'Raise them to at least horizontal with a posterior pelvic tilt.',
      'Lower under control.',
    ],
    commonMistakes: ['Kipping.', 'Pure hip flexion without spinal curl.'],
    scienceExplanation:
      'The long lever makes bodyweight a heavy ab load, progressing the hanging raise family.',
    progressionInstructions: 'Slow the negative, then add ankle weights.',
    easierAlternatives: ['hanging-knee-raise'],
  }),
  defineExercise({
    slug: 'reverse-crunch',
    name: 'Reverse Crunch',
    description: 'Lying pelvic curl bringing knees to chest.',
    primaryMuscles: ['abs'],
    equipment: ['bodyweight'],
    movementPattern: 'ab_flexion',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    trackingType: 'bodyweight_reps',
    instructions: [
      'Lie on your back, knees bent over hips.',
      'Curl your pelvis up, lifting the hips off the floor.',
      'Lower slowly.',
    ],
    commonMistakes: ['Swinging the legs for momentum.'],
    scienceExplanation:
      'Loads the abs through pelvic tilt with no equipment and minimal hip-flexor takeover.',
    progressionInstructions: 'Slow the lowering phase, then progress to hanging raises.',
    harderAlternatives: ['hanging-knee-raise'],
    equivalentAlternatives: ['weighted-crunch'],
  }),
  defineExercise({
    slug: 'plank',
    name: 'Plank',
    description: 'Isometric anti-extension hold on the forearms.',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['shoulders', 'glutes'],
    equipment: ['bodyweight'],
    movementPattern: 'anti_extension',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    trackingType: 'time',
    instructions: [
      'Forearms and toes on the floor, body in a straight line.',
      'Squeeze glutes and brace the abs; breathe steadily.',
    ],
    commonMistakes: ['Hips sagging or piking.', 'Holding past the point of good position.'],
    scienceExplanation:
      'Trains the core to resist spinal extension — the bracing skill that protects your squats, rows, and presses.',
    progressionInstructions:
      'Extend hold time to ~60 s, then progress to harder variations rather than longer holds.',
    harderAlternatives: ['ab-wheel-rollout'],
    equivalentAlternatives: ['ab-wheel-rollout'],
  }),
  defineExercise({
    slug: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    description: 'Kneeling rollout — anti-extension under a moving lever.',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['shoulders', 'back'],
    equipment: ['bodyweight'],
    movementPattern: 'anti_extension',
    difficulty: 'intermediate',
    exerciseType: 'isolation',
    trackingType: 'bodyweight_reps',
    instructions: [
      'Kneel holding the wheel below your shoulders.',
      'Roll forward keeping the abs braced and back flat.',
      'Pull back with the lats and abs.',
    ],
    commonMistakes: ['Lower back sagging into extension.', 'Rolling further than you can control.'],
    scienceExplanation:
      'Progressively lengthens the anti-extension lever, loading the abs far harder than static planks.',
    progressionInstructions: 'Increase range gradually toward full standing rollouts.',
    easierAlternatives: ['plank'],
  }),
  defineExercise({
    slug: 'pallof-press',
    name: 'Pallof Press',
    description: 'Anti-rotation cable or band press-out.',
    primaryMuscles: ['abs'],
    equipment: ['cable_machine', 'resistance_band'],
    movementPattern: 'anti_rotation',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    laterality: 'unilateral',
    instructions: [
      'Stand side-on to a cable at chest height, holding it at your sternum.',
      'Press straight out, resisting the pull toward the machine.',
      'Return with control; repeat both sides.',
    ],
    commonMistakes: ['Twisting toward the load.', 'Standing too upright and stiff-kneed.'],
    scienceExplanation:
      'Trains the obliques to resist rotation — core stability that carries over to unilateral and standing lifts.',
    progressionInstructions: 'Small load steps or a longer press-out pause.',
    equivalentAlternatives: ['plank'],
  }),
] as const;
