import { defineExercise } from '../define';

export const chestExercises = [
  defineExercise({
    slug: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    aliases: ['Flat Bench Press', 'Bench'],
    description: 'The classic barbell press for overall chest, front delt, and triceps mass.',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['barbell', 'bench', 'squat_rack'],
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    instructions: [
      'Lie on the bench with eyes under the bar, feet planted, shoulder blades pulled back and down.',
      'Grip slightly wider than shoulder width and unrack with straight arms.',
      'Lower the bar under control to the mid-chest, elbows about 45–60° from the torso.',
      'Press back up to lockout without bouncing off the chest.',
    ],
    commonMistakes: [
      'Bouncing the bar off the chest.',
      'Letting the elbows flare to 90° and losing shoulder stability.',
      'Lifting the hips off the bench to press more weight.',
    ],
    scienceExplanation:
      'A heavily loadable horizontal press that trains the pecs through a large range with high mechanical tension — the main driver of hypertrophy.',
    progressionInstructions:
      'Work in the prescribed rep range; when every set hits the top of the range at the target RIR, add the smallest plate increment and restart at the bottom of the range.',
    easierAlternatives: ['machine-chest-press', 'dumbbell-bench-press'],
    harderAlternatives: [],
    equivalentAlternatives: ['dumbbell-bench-press', 'smith-machine-bench-press'],
  }),
  defineExercise({
    slug: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    description: 'Flat dumbbell press allowing a freer arm path and longer range than the barbell.',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['dumbbell', 'bench'],
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: [
      'Sit with dumbbells on your thighs, then kick them up as you lie back.',
      'Set your shoulder blades and plant your feet.',
      'Lower the dumbbells to the sides of your chest with a comfortable elbow path.',
      'Press up and slightly inward until arms are extended.',
    ],
    commonMistakes: [
      'Cutting the range short at the bottom.',
      'Clanging the dumbbells together at the top.',
      'Using dumbbells too heavy to control into position.',
    ],
    scienceExplanation:
      'The independent arm path lets you stretch the pecs deeper at the bottom, and training at long muscle lengths is a strong hypertrophy stimulus.',
    progressionInstructions:
      'Double progression: earn the top of the rep range on all sets, then move up one dumbbell step and rebuild reps.',
    easierAlternatives: ['machine-chest-press'],
    harderAlternatives: ['barbell-bench-press'],
    equivalentAlternatives: ['barbell-bench-press', 'machine-chest-press'],
  }),
  defineExercise({
    slug: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    description: 'A 30–45° incline press biasing the upper chest fibers.',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['dumbbell', 'incline_bench'],
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: [
      'Set the bench to a 30–45° incline.',
      'Kick the dumbbells up and set your shoulder blades.',
      'Lower to the upper chest until you feel a stretch.',
      'Press up and slightly together without losing back tightness.',
    ],
    commonMistakes: [
      'Setting the incline so steep it becomes a shoulder press.',
      'Flaring the elbows straight out.',
      'Arching so much the incline is lost.',
    ],
    scienceExplanation:
      'The incline shifts emphasis to the clavicular (upper) pec fibers while still allowing a flexible arm path and deep stretch.',
    progressionInstructions:
      'Hit the top of the rep range at target RIR on all sets before taking the next dumbbell step.',
    easierAlternatives: ['machine-chest-press'],
    harderAlternatives: ['incline-barbell-press'],
    equivalentAlternatives: ['incline-barbell-press'],
  }),
  defineExercise({
    slug: 'incline-barbell-press',
    name: 'Incline Barbell Press',
    description: 'Barbell press on a low incline for upper-chest focused heavy loading.',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['barbell', 'incline_bench', 'squat_rack'],
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    instructions: [
      'Set a 30° incline in a rack and lie with the bar over your upper chest.',
      'Grip slightly wider than shoulders, set your shoulder blades, unrack.',
      'Lower to just below the collarbone under control.',
      'Press up without letting the bar drift forward over the face.',
    ],
    commonMistakes: [
      'Bouncing off the upper chest.',
      'Using the flat-bench arch and losing the incline benefit.',
    ],
    scienceExplanation:
      'Combines upper-chest emphasis with barbell-level loading, letting you apply progressive overload in small, precise steps.',
    progressionInstructions:
      'Add the smallest plate increment once all sets reach the top of the range at target RIR.',
    easierAlternatives: ['incline-dumbbell-press', 'machine-chest-press'],
    equivalentAlternatives: ['incline-dumbbell-press'],
  }),
  defineExercise({
    slug: 'machine-chest-press',
    name: 'Machine Chest Press',
    description: 'A guided pressing machine, ideal for stable, low-setup chest volume.',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['selectorized_machine', 'plate_loaded_machine'],
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: [
      'Set the seat so handles line up with mid-chest.',
      'Keep shoulder blades back against the pad.',
      'Press to full extension without shrugging.',
      'Lower slowly until you feel a chest stretch.',
    ],
    commonMistakes: ['Seat set too low or high.', 'Shrugging shoulders forward at lockout.'],
    scienceExplanation:
      'The fixed path removes the stability demand, letting you push the chest closer to failure safely — useful for productive volume, especially late in a session.',
    progressionInstructions:
      'Progress one stack pin at a time after topping the rep range on all sets.',
    harderAlternatives: ['barbell-bench-press', 'dumbbell-bench-press'],
    equivalentAlternatives: ['dumbbell-bench-press'],
  }),
  defineExercise({
    slug: 'smith-machine-bench-press',
    name: 'Smith Machine Bench Press',
    description: 'Bench press on a guided bar path for stable heavy pressing.',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['smith_machine', 'bench'],
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: [
      'Set the bench so the bar touches mid-chest at the bottom.',
      'Set shoulder blades, unrack by rotating the hooks.',
      'Lower under control and press to lockout.',
    ],
    commonMistakes: ['Bench positioned so the bar path hits the wrong chest point.'],
    scienceExplanation:
      'The fixed path trades some stabilizer work for the ability to safely train close to failure without a spotter.',
    progressionInstructions:
      'Add the smallest available load increment when all sets top the rep range at target RIR.',
    equivalentAlternatives: ['barbell-bench-press', 'machine-chest-press'],
  }),
  defineExercise({
    slug: 'push-up',
    name: 'Push-Up',
    description: 'The fundamental bodyweight horizontal press.',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    equipment: ['bodyweight'],
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    exerciseType: 'compound',
    trackingType: 'bodyweight_reps',
    instructions: [
      'Hands slightly wider than shoulders, body in a straight line.',
      'Lower until your chest nearly touches the floor.',
      'Press back up without letting the hips sag.',
    ],
    commonMistakes: ['Sagging hips.', 'Half-range reps.', 'Elbows flared to 90°.'],
    scienceExplanation:
      'A scalable pressing pattern; elevating feet or adding load keeps it in a productive rep range as you get stronger.',
    progressionInstructions:
      'Add reps first; when they exceed the target range, elevate your feet or add load (backpack or plate) and return to the bottom of the range.',
    easierAlternatives: ['incline-push-up'],
    harderAlternatives: ['deficit-push-up', 'weighted-push-up'],
  }),
  defineExercise({
    slug: 'incline-push-up',
    name: 'Incline Push-Up',
    description: 'Push-up with hands elevated to reduce load — a friendly entry point.',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['bodyweight'],
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    exerciseType: 'compound',
    trackingType: 'bodyweight_reps',
    instructions: [
      'Place hands on a stable elevated surface (bench, box, counter).',
      'Keep a straight body line and lower your chest to the edge.',
      'Press back to full extension.',
    ],
    commonMistakes: ['Hips sagging or piking.', 'Hands set too low too soon.'],
    scienceExplanation:
      'Raising the hands reduces the percentage of bodyweight lifted, keeping reps inside an effective range while you build pressing strength.',
    progressionInstructions: 'Lower the hand surface over time until you reach floor push-ups.',
    harderAlternatives: ['push-up'],
  }),
  defineExercise({
    slug: 'deficit-push-up',
    name: 'Deficit Push-Up',
    description: 'Push-up with hands on handles or plates for extra range and stretch.',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['bodyweight'],
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    trackingType: 'bodyweight_reps',
    instructions: [
      'Set hands on elevated handles or plates.',
      'Lower your chest below hand level for a deep stretch.',
      'Press up keeping a rigid body line.',
    ],
    commonMistakes: ['Rushing the stretch position.', 'Shoulders rolling forward at depth.'],
    scienceExplanation:
      'The added depth loads the pecs at longer muscle lengths, which research links to greater growth per rep.',
    progressionInstructions: 'Add reps, then load with a backpack or weighted vest.',
    easierAlternatives: ['push-up'],
    harderAlternatives: ['weighted-push-up'],
  }),
  defineExercise({
    slug: 'weighted-push-up',
    name: 'Weighted Push-Up',
    description: 'Push-up loaded with a plate or backpack for continued overload.',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['bodyweight'],
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    trackingType: 'weighted_bodyweight',
    instructions: [
      'Load a backpack or have a plate placed on your upper back.',
      'Perform strict full-range push-ups.',
    ],
    commonMistakes: ['Load sliding onto the lower back.', 'Shortened range under load.'],
    scienceExplanation:
      'External load restores a hypertrophy-effective rep range once bodyweight push-ups become too easy.',
    progressionInstructions: 'Add small load increments once all sets top the rep range.',
    easierAlternatives: ['push-up'],
  }),
  defineExercise({
    slug: 'cable-fly',
    name: 'Cable Fly',
    aliases: ['Cable Crossover'],
    description: 'Standing cable fly keeping tension on the pecs through the full arc.',
    primaryMuscles: ['chest'],
    equipment: ['cable_machine'],
    movementPattern: 'chest_fly',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Set pulleys at chest height, take one handle in each hand, step forward.',
      'With a slight elbow bend, open your arms until you feel a pec stretch.',
      'Sweep the handles together in a hugging arc.',
    ],
    commonMistakes: [
      'Turning it into a press by bending the elbows.',
      'Using momentum from the torso.',
    ],
    scienceExplanation:
      'Cables keep resistance on the pecs even at the squeezed position, complementing presses which lose tension at lockout.',
    progressionInstructions: 'Progress load in small stack increments; prioritize a deep stretch.',
    equivalentAlternatives: ['dumbbell-fly', 'pec-deck'],
  }),
  defineExercise({
    slug: 'pec-deck',
    name: 'Pec Deck Fly',
    aliases: ['Machine Fly'],
    description: 'Machine fly isolating the chest with minimal setup or stability demand.',
    primaryMuscles: ['chest'],
    equipment: ['selectorized_machine'],
    movementPattern: 'chest_fly',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Set the seat so handles are at mid-chest height.',
      'With slightly bent elbows, bring the handles together.',
      'Open slowly until you feel a comfortable stretch.',
    ],
    commonMistakes: ['Letting shoulders roll forward.', 'Slamming the stack between reps.'],
    scienceExplanation:
      'The fixed arc isolates the pecs and is easy to push close to failure safely — a good high-rep finisher.',
    progressionInstructions: 'One stack pin at a time after topping the rep range.',
    equivalentAlternatives: ['cable-fly', 'dumbbell-fly'],
  }),
  defineExercise({
    slug: 'dumbbell-fly',
    name: 'Dumbbell Fly',
    description: 'Lying dumbbell fly emphasizing the stretched position of the pecs.',
    primaryMuscles: ['chest'],
    equipment: ['dumbbell', 'bench'],
    movementPattern: 'chest_fly',
    difficulty: 'intermediate',
    exerciseType: 'isolation',
    instructions: [
      'Lie on a flat bench with dumbbells over your chest, palms facing.',
      'Lower in a wide arc with a fixed slight elbow bend.',
      'Stop at a strong stretch, then sweep back up.',
    ],
    commonMistakes: [
      'Going too heavy and pressing instead of flying.',
      'Overstretching at the bottom.',
    ],
    scienceExplanation:
      'Maximally loads the pec stretch; keep loads moderate since tension at the bottom is highest exactly where you are weakest.',
    progressionInstructions: 'Small dumbbell steps; add reps before load.',
    equivalentAlternatives: ['cable-fly', 'pec-deck'],
  }),
  defineExercise({
    slug: 'dip',
    name: 'Chest Dip',
    aliases: ['Parallel Bar Dip'],
    description: 'Bodyweight dip with forward lean targeting the lower chest and triceps.',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['dip_station'],
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    trackingType: 'weighted_bodyweight',
    instructions: [
      'Support yourself on parallel bars, lean the torso slightly forward.',
      'Lower until your upper arms are about parallel to the floor.',
      'Press back up without fully locking out harshly.',
    ],
    commonMistakes: [
      'Descending too fast and too deep for your shoulder mobility.',
      'Staying bolt upright (shifts load to triceps).',
    ],
    scienceExplanation:
      'A big-range press loading the pecs deep in the stretch; easily overloaded with a dip belt for years of progression.',
    progressionInstructions: 'Add reps to the top of the range, then add weight with a belt.',
    easierAlternatives: ['machine-chest-press', 'push-up'],
  }),
] as const;
