import { defineExercise } from '../define';

export const legExercises = [
  // --- Squat pattern ------------------------------------------------------
  defineExercise({
    slug: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    description: 'The barbell squat — the highest-loading quad and glute builder.',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'lower_back', 'abs'],
    equipment: ['barbell', 'squat_rack'],
    movementPattern: 'squat',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    instructions: [
      'Set the bar on your upper traps, brace, and unrack.',
      'Sit down between your hips with a tall chest until thighs reach at least parallel.',
      'Drive up through mid-foot, keeping knees tracking over toes.',
    ],
    commonMistakes: [
      'Knees caving inward.',
      'Rising hips-first into a good-morning.',
      'Cutting depth as weight increases.',
    ],
    scienceExplanation:
      'Loads the quads and glutes through the biggest usable range with the most progression headroom of any lower-body lift.',
    progressionInstructions:
      'Add the smallest plate increment when all sets top the rep range at target RIR.',
    easierAlternatives: ['goblet-squat', 'leg-press', 'smith-machine-squat'],
    equivalentAlternatives: ['hack-squat-machine', 'smith-machine-squat'],
  }),
  defineExercise({
    slug: 'goblet-squat',
    name: 'Goblet Squat',
    description: 'Squat holding a dumbbell or kettlebell at the chest — self-correcting form.',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'abs'],
    equipment: ['dumbbell', 'kettlebell'],
    movementPattern: 'squat',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: [
      'Hold a dumbbell vertically against your chest.',
      'Squat down keeping elbows inside the knees, chest tall.',
      'Drive back up through mid-foot.',
    ],
    commonMistakes: ['Letting the weight pull the chest forward.', 'Heels lifting.'],
    scienceExplanation:
      'The front-loaded counterbalance keeps the torso upright, teaching deep squatting while genuinely loading the quads.',
    progressionInstructions:
      'Dumbbell steps until the heaviest bell is easy — then graduate to barbell or hack squats.',
    harderAlternatives: ['barbell-back-squat', 'hack-squat-machine'],
    equivalentAlternatives: ['leg-press'],
  }),
  defineExercise({
    slug: 'smith-machine-squat',
    name: 'Smith Machine Squat',
    description: 'Guided-bar squat allowing foot placement ahead of the bar path.',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes'],
    equipment: ['smith_machine'],
    movementPattern: 'squat',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: [
      'Set the bar on your traps, feet slightly ahead of the bar line.',
      'Squat to at least parallel and drive up.',
    ],
    commonMistakes: ['Feet directly under the bar forcing knee strain.'],
    scienceExplanation:
      'The fixed path removes balance demands so the quads can be pushed near failure with less technical risk.',
    progressionInstructions:
      'Add the smallest practical load increment once all sets top the range.',
    equivalentAlternatives: ['barbell-back-squat', 'hack-squat-machine', 'leg-press'],
  }),
  defineExercise({
    slug: 'hack-squat-machine',
    name: 'Hack Squat',
    description: 'Machine squat with back support for deep, quad-focused loading.',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes'],
    equipment: ['hack_squat'],
    movementPattern: 'squat',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    instructions: [
      'Set your back against the pad, feet mid-platform.',
      'Lower deep with knees tracking over toes.',
      'Press up without locking out harshly.',
    ],
    commonMistakes: [
      'Feet too high (shifts to glutes when quads are the target).',
      'Shallow reps.',
    ],
    scienceExplanation:
      'Back support plus a guided path lets you take the quads through deep ranges close to failure safely — hard to beat for quad hypertrophy.',
    progressionInstructions: 'Add the smallest plate increment after topping the rep range.',
    equivalentAlternatives: ['leg-press', 'barbell-back-squat'],
  }),
  defineExercise({
    slug: 'leg-press',
    name: 'Leg Press',
    description: 'Sled press for heavy quad and glute work without spinal loading.',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['leg_press'],
    movementPattern: 'squat',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: [
      'Feet shoulder-width at mid-platform.',
      'Lower until knees approach your chest without the lower back rounding off the pad.',
      'Press through mid-foot, stopping just short of harsh lockout.',
    ],
    commonMistakes: ['Butt lifting off the pad at depth.', 'Tiny half reps with excessive load.'],
    scienceExplanation:
      'Removes the balance and spinal-loading limits of squats so the quads themselves become the limiting factor.',
    progressionInstructions:
      'Add plates in the smallest steps after topping the range on all sets.',
    equivalentAlternatives: ['hack-squat-machine', 'barbell-back-squat'],
  }),
  defineExercise({
    slug: 'leg-extension',
    name: 'Leg Extension',
    description: 'Machine knee extension isolating the quads.',
    primaryMuscles: ['quadriceps'],
    equipment: ['selectorized_machine'],
    movementPattern: 'knee_extension',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Set the pad on your shins, knees aligned with the machine pivot.',
      'Extend to straight legs and squeeze.',
      'Lower with a slow negative.',
    ],
    commonMistakes: ['Slamming the stack.', 'Hips lifting off the seat.'],
    scienceExplanation:
      'The only common movement loading the rectus femoris hard at short hip flexion — direct quad isolation squats cannot replicate.',
    progressionInstructions: 'One pin at a time; a controlled negative matters more than load.',
    equivalentAlternatives: ['sissy-squat'],
  }),
  defineExercise({
    slug: 'sissy-squat',
    name: 'Sissy Squat',
    description: 'Bodyweight quad isolation leaning back on the knees.',
    primaryMuscles: ['quadriceps'],
    equipment: ['bodyweight'],
    movementPattern: 'knee_extension',
    difficulty: 'advanced',
    exerciseType: 'isolation',
    trackingType: 'bodyweight_reps',
    instructions: [
      'Hold support with one hand, rise onto your toes.',
      'Lean back and bend the knees, letting them travel forward.',
      'Return by extending the knees.',
    ],
    commonMistakes: ['Bending at the hips (turns it into a squat).', 'Dropping too deep too soon.'],
    scienceExplanation:
      'Loads the quads in a deep stretch using bodyweight alone — a machine-free stand-in for leg extensions.',
    progressionInstructions: 'Increase depth gradually, then hold a plate.',
    easierAlternatives: ['goblet-squat'],
    equivalentAlternatives: ['leg-extension'],
  }),
  // --- Hinge / hamstrings / glutes ---------------------------------------
  defineExercise({
    slug: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    aliases: ['RDL'],
    description: 'Hip hinge with soft knees stretching and loading the hamstrings.',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'lower_back', 'forearms'],
    equipment: ['barbell', 'dumbbell'],
    movementPattern: 'hip_hinge',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    instructions: [
      'Hold the bar at your thighs, shoulders back, knees slightly bent.',
      'Push your hips back, sliding the bar down your legs with a flat back.',
      'Stop when the hamstrings are fully stretched, then drive hips forward.',
    ],
    commonMistakes: [
      'Rounding the back.',
      'Bending the knees into a squat.',
      'Overreaching past hamstring flexibility.',
    ],
    scienceExplanation:
      'Loads the hamstrings at long muscle lengths under heavy load — one of the strongest hypertrophy signals available for the posterior chain.',
    progressionInstructions: 'Smallest plate increments once all sets top the range at target RIR.',
    easierAlternatives: ['dumbbell-rdl', 'back-extension'],
    equivalentAlternatives: ['dumbbell-rdl'],
  }),
  defineExercise({
    slug: 'dumbbell-rdl',
    name: 'Dumbbell Romanian Deadlift',
    description: 'RDL holding dumbbells — friendlier setup, same hamstring stretch.',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'lower_back'],
    equipment: ['dumbbell', 'adjustable_dumbbell', 'kettlebell'],
    movementPattern: 'hip_hinge',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: [
      'Dumbbells at your thighs, soft knees.',
      'Hinge back until the hamstrings stretch, back flat.',
      'Stand by driving the hips forward.',
    ],
    commonMistakes: ['Rounding the upper back around the dumbbells.', 'Squatting the weight down.'],
    scienceExplanation:
      'Identical stretch-loaded hinge stimulus to the barbell version with easier grip and setup for home training.',
    progressionInstructions: 'Dumbbell steps after topping the rep range.',
    harderAlternatives: ['romanian-deadlift'],
    equivalentAlternatives: ['romanian-deadlift', 'back-extension'],
  }),
  defineExercise({
    slug: 'seated-leg-curl',
    name: 'Seated Leg Curl',
    description: 'Machine knee flexion with the hips flexed for a long hamstring stretch.',
    primaryMuscles: ['hamstrings'],
    equipment: ['selectorized_machine'],
    movementPattern: 'knee_flexion',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Set the pads, legs extended, thighs secured.',
      'Curl your heels under the seat as far as possible.',
      'Return slowly to a full stretch.',
    ],
    commonMistakes: ['Hips rising to cheat the weight.', 'Short mid-range pumping reps.'],
    scienceExplanation:
      'The seated (hip-flexed) position lengthens the hamstrings so they are trained under stretch — shown to outgrow lying curls.',
    progressionInstructions: 'One pin at a time; full range is non-negotiable.',
    equivalentAlternatives: ['lying-leg-curl', 'nordic-curl'],
  }),
  defineExercise({
    slug: 'lying-leg-curl',
    name: 'Lying Leg Curl',
    description: 'Prone machine curl for direct hamstring work.',
    primaryMuscles: ['hamstrings'],
    equipment: ['selectorized_machine', 'plate_loaded_machine'],
    movementPattern: 'knee_flexion',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Lie prone with the pad at your ankles.',
      'Curl to full knee flexion, lower slowly.',
    ],
    commonMistakes: ['Hips popping up.', 'Fast, bouncy reps.'],
    scienceExplanation:
      'Isolates knee flexion, complementing hinge work which loads the hamstrings mainly at the hip.',
    progressionInstructions: 'Small pin steps after topping the range.',
    equivalentAlternatives: ['seated-leg-curl', 'slider-leg-curl'],
  }),
  defineExercise({
    slug: 'nordic-curl',
    name: 'Nordic Hamstring Curl',
    description: 'Kneeling eccentric hamstring curl — brutally effective bodyweight option.',
    primaryMuscles: ['hamstrings'],
    equipment: ['bodyweight'],
    movementPattern: 'knee_flexion',
    difficulty: 'advanced',
    exerciseType: 'isolation',
    trackingType: 'bodyweight_reps',
    instructions: [
      'Kneel with ankles anchored under something solid.',
      'Lower your torso forward as slowly as possible.',
      'Push back up with hands as needed and curl back to the start.',
    ],
    commonMistakes: ['Breaking at the hips.', 'Dropping instead of resisting.'],
    scienceExplanation:
      'Emphasizes heavy eccentric knee flexion, building hamstring size and resilience with no equipment.',
    progressionInstructions: 'Slow the negative, reduce hand assistance, add range over time.',
    easierAlternatives: ['slider-leg-curl', 'lying-leg-curl'],
  }),
  defineExercise({
    slug: 'slider-leg-curl',
    name: 'Slider Leg Curl',
    description: 'Supine leg curl sliding the heels — hamstrings with zero equipment.',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'abs'],
    equipment: ['bodyweight'],
    movementPattern: 'knee_flexion',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    trackingType: 'bodyweight_reps',
    instructions: [
      'Lie on your back, heels on sliders or a towel on a smooth floor.',
      'Bridge your hips up and curl your heels toward you.',
      'Extend back out slowly without dropping the hips.',
    ],
    commonMistakes: ['Hips sagging as legs extend.'],
    scienceExplanation:
      'Trains hip extension and knee flexion together, mimicking a lying curl with household equipment.',
    progressionInstructions: 'Add reps, slow the eccentric, progress to single-leg.',
    harderAlternatives: ['nordic-curl'],
    equivalentAlternatives: ['lying-leg-curl'],
  }),
  defineExercise({
    slug: 'hip-thrust',
    name: 'Barbell Hip Thrust',
    description: 'Back-on-bench hip extension for maximal glute loading.',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'quadriceps'],
    equipment: ['barbell', 'bench'],
    movementPattern: 'hip_thrust',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: [
      'Upper back on a bench, bar padded over your hips.',
      'Drive your hips to full extension with a posterior pelvic tilt.',
      'Lower until the plates nearly touch and repeat.',
    ],
    commonMistakes: ['Overarching the lower back at lockout.', 'Pushing through the toes.'],
    scienceExplanation:
      'Loads the glutes hardest at full hip extension where squats unload — direct tension exactly where glutes work most.',
    progressionInstructions: 'Add plates in small steps after topping the rep range.',
    easierAlternatives: ['glute-bridge'],
    equivalentAlternatives: ['glute-bridge', 'machine-hip-thrust'],
  }),
  defineExercise({
    slug: 'glute-bridge',
    name: 'Glute Bridge',
    description: 'Floor hip extension — the accessible entry to direct glute training.',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight', 'dumbbell'],
    movementPattern: 'hip_thrust',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    trackingType: 'weighted_bodyweight',
    instructions: [
      'Lie on your back, knees bent, feet flat.',
      'Drive hips up squeezing the glutes.',
      'Lower with control.',
    ],
    commonMistakes: ['Arching the lower back instead of extending the hips.'],
    scienceExplanation:
      'Teaches loaded hip extension; adding a dumbbell over the hips keeps it productive well past the beginner phase.',
    progressionInstructions: 'Add reps, then a dumbbell over the hips, then move to hip thrusts.',
    harderAlternatives: ['hip-thrust'],
  }),
  defineExercise({
    slug: 'machine-hip-thrust',
    name: 'Machine Hip Thrust',
    description: 'Plate-loaded hip thrust with fast setup.',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['plate_loaded_machine'],
    movementPattern: 'hip_thrust',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: ['Set your back on the pad, belt over hips, drive to full extension.'],
    commonMistakes: ['Cutting the lockout short.'],
    scienceExplanation:
      'Same glute-dominant hip extension as the barbell version without the awkward barbell setup.',
    progressionInstructions: 'Smallest plate increments after topping the range.',
    equivalentAlternatives: ['hip-thrust'],
  }),
  // --- Unilateral lower body ----------------------------------------------
  defineExercise({
    slug: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    aliases: ['Rear-Foot-Elevated Split Squat'],
    description: 'Rear-foot-elevated single-leg squat for quads and glutes.',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['dumbbell', 'bench', 'bodyweight'],
    movementPattern: 'lunge',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    laterality: 'unilateral',
    instructions: [
      'Rear foot on a bench, front foot far enough forward to squat comfortably.',
      'Lower until the front thigh reaches parallel.',
      'Drive up through the front mid-foot.',
    ],
    commonMistakes: ['Front foot too close to the bench.', 'Pushing off the back leg.'],
    scienceExplanation:
      'Delivers near-barbell-squat leg stimulus per leg with far less spinal load, while training balance and addressing side-to-side gaps.',
    progressionInstructions: 'Add reps, then hold heavier dumbbells.',
    easierAlternatives: ['split-squat', 'walking-lunge'],
    equivalentAlternatives: ['walking-lunge', 'step-up'],
  }),
  defineExercise({
    slug: 'split-squat',
    name: 'Split Squat',
    description: 'Static lunge-stance squat — the entry point to unilateral training.',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes'],
    equipment: ['bodyweight', 'dumbbell'],
    movementPattern: 'lunge',
    difficulty: 'beginner',
    exerciseType: 'compound',
    laterality: 'unilateral',
    instructions: [
      'Take a long stride stance.',
      'Lower the back knee toward the floor.',
      'Drive up through the front foot.',
    ],
    commonMistakes: [
      'Short stance driving the knee far past the toes uncomfortably.',
      'Leaning far forward.',
    ],
    scienceExplanation:
      'Builds single-leg strength and balance with a stable setup before progressing to rear-foot-elevated work.',
    progressionInstructions: 'Add dumbbells, then elevate the rear foot.',
    harderAlternatives: ['bulgarian-split-squat', 'walking-lunge'],
  }),
  defineExercise({
    slug: 'walking-lunge',
    name: 'Walking Lunge',
    description: 'Alternating forward lunges for quads, glutes, and conditioning.',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['bodyweight', 'dumbbell'],
    movementPattern: 'lunge',
    difficulty: 'beginner',
    exerciseType: 'compound',
    laterality: 'unilateral',
    instructions: [
      'Step forward into a lunge, back knee toward the floor.',
      'Push through the front foot into the next stride.',
    ],
    commonMistakes: [
      'Short strides with the torso pitched forward.',
      'Wobbling from a narrow base.',
    ],
    scienceExplanation:
      'High-rep unilateral volume with a stretch on the trailing leg glutes each stride.',
    progressionInstructions: 'Add dumbbells once bodyweight sets top the range.',
    equivalentAlternatives: ['bulgarian-split-squat', 'step-up'],
  }),
  defineExercise({
    slug: 'step-up',
    name: 'Dumbbell Step-Up',
    description: 'Step onto a box or bench driving through one leg.',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes'],
    equipment: ['bench', 'dumbbell', 'bodyweight'],
    movementPattern: 'lunge',
    difficulty: 'beginner',
    exerciseType: 'compound',
    laterality: 'unilateral',
    instructions: [
      'Place one whole foot on a knee-height box.',
      'Drive up through that leg without springing off the floor leg.',
      'Lower under control.',
    ],
    commonMistakes: ['Bouncing off the bottom leg.', 'Box too high for control.'],
    scienceExplanation:
      'Concentric-focused single-leg work that is easy on the knees and builds real-world stepping strength.',
    progressionInstructions: 'Raise the box or hold heavier dumbbells.',
    equivalentAlternatives: ['bulgarian-split-squat', 'walking-lunge'],
  }),
] as const;
