import { defineExercise } from '../define';

export const shoulderExercises = [
  defineExercise({
    slug: 'overhead-press',
    name: 'Barbell Overhead Press',
    aliases: ['Military Press', 'OHP'],
    description: 'Standing barbell press — the foundational vertical push for delts and triceps.',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'abs'],
    equipment: ['barbell', 'squat_rack'],
    movementPattern: 'vertical_push',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    instructions: [
      'Take the bar at collarbone height, grip just outside shoulders.',
      'Brace your glutes and abs, press the bar overhead.',
      'Finish with the bar over the back of your head, then lower to the collarbone.',
    ],
    commonMistakes: ['Leaning back into an incline press.', 'Pressing around the chin instead of moving the head back.', 'No leg/glute brace.'],
    scienceExplanation:
      'Loads the front and side delts through a long overhead range with barbell-level progression precision.',
    progressionInstructions: 'Add the smallest increment when all sets top the rep range at target RIR.',
    easierAlternatives: ['seated-dumbbell-press', 'machine-shoulder-press'],
    equivalentAlternatives: ['seated-dumbbell-press'],
  }),
  defineExercise({
    slug: 'seated-dumbbell-press',
    name: 'Seated Dumbbell Shoulder Press',
    description: 'Supported dumbbell press with a natural arm path for delt growth.',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell', 'incline_bench'],
    movementPattern: 'vertical_push',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: [
      'Set the bench nearly upright, kick the dumbbells to shoulder height.',
      'Press up and slightly together to lockout.',
      'Lower until the dumbbells reach about ear level or a comfortable stretch.',
    ],
    commonMistakes: ['Flaring the dumbbells far behind the head.', 'Cutting the bottom range.'],
    scienceExplanation:
      'The back support and free arm path let you train delts close to failure with less lower-back involvement than standing presses.',
    progressionInstructions: 'One dumbbell step after topping the rep range on all sets.',
    easierAlternatives: ['machine-shoulder-press'],
    harderAlternatives: ['overhead-press'],
    equivalentAlternatives: ['overhead-press', 'machine-shoulder-press'],
  }),
  defineExercise({
    slug: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    description: 'Guided overhead press for stable, joint-friendly delt volume.',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['selectorized_machine', 'plate_loaded_machine'],
    movementPattern: 'vertical_push',
    difficulty: 'beginner',
    exerciseType: 'compound',
    instructions: [
      'Set the seat so handles start at shoulder height.',
      'Press to lockout without shrugging.',
      'Lower under control to the start.',
    ],
    commonMistakes: ['Seat too low forcing an awkward start.', 'Shrugging at lockout.'],
    scienceExplanation:
      'The machine removes the balance demand, making near-failure sets safer — where the growth-driving reps live.',
    progressionInstructions: 'One stack pin at a time after topping the range.',
    harderAlternatives: ['overhead-press', 'seated-dumbbell-press'],
    equivalentAlternatives: ['seated-dumbbell-press'],
  }),
  defineExercise({
    slug: 'pike-push-up',
    name: 'Pike Push-Up',
    description: 'Bodyweight vertical-press pattern loading the shoulders in a pike position.',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['bodyweight'],
    movementPattern: 'vertical_push',
    difficulty: 'intermediate',
    exerciseType: 'compound',
    trackingType: 'bodyweight_reps',
    instructions: [
      'From a push-up position, walk your feet in and raise your hips high.',
      'Lower the top of your head toward the floor between your hands.',
      'Press back to the pike position.',
    ],
    commonMistakes: ['Turning it into a normal push-up by dropping the hips.', 'Banging the head on the floor.'],
    scienceExplanation:
      'Shifts bodyweight onto the delts in a vertical pressing line — the bodyweight equivalent of an overhead press.',
    progressionInstructions: 'Add reps, then elevate the feet to increase loading.',
    easierAlternatives: ['push-up'],
    equivalentAlternatives: ['seated-dumbbell-press'],
  }),
  defineExercise({
    slug: 'lateral-raise',
    name: 'Dumbbell Lateral Raise',
    description: 'The staple side-delt isolation for shoulder width.',
    primaryMuscles: ['shoulders'],
    equipment: ['dumbbell'],
    movementPattern: 'shoulder_abduction',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Stand holding light dumbbells at your sides, slight elbow bend.',
      'Raise your arms out to shoulder height, leading with the elbows.',
      'Lower slowly — the negative is half the exercise.',
    ],
    commonMistakes: ['Swinging with the hips.', 'Shrugging traps into the raise.', 'Going above shoulder height with internal rotation.'],
    scienceExplanation:
      'Directly targets the medial delt, the muscle that most defines shoulder width and gets limited work from presses alone.',
    progressionInstructions: 'Progress reps well before load; side delts respond to high-quality, higher-rep sets.',
    equivalentAlternatives: ['cable-lateral-raise', 'machine-lateral-raise'],
  }),
  defineExercise({
    slug: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    description: 'Single-arm cable raise with tension from the very bottom of the range.',
    primaryMuscles: ['shoulders'],
    equipment: ['cable_machine'],
    movementPattern: 'shoulder_abduction',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    laterality: 'unilateral',
    instructions: [
      'Set the pulley at the lowest position, stand side-on.',
      'Raise the handle across your body out to shoulder height.',
      'Lower slowly against the cable.',
    ],
    commonMistakes: ['Leaning away excessively.', 'Jerking the start of each rep.'],
    scienceExplanation:
      'Unlike dumbbells, the cable loads the delt even at the bottom of the arc, increasing time under tension per set.',
    progressionInstructions: 'Small stack increments; strict form beats load here.',
    equivalentAlternatives: ['lateral-raise', 'machine-lateral-raise'],
  }),
  defineExercise({
    slug: 'machine-lateral-raise',
    name: 'Machine Lateral Raise',
    description: 'Machine-guided side raise that removes all cheating momentum.',
    primaryMuscles: ['shoulders'],
    equipment: ['selectorized_machine'],
    movementPattern: 'shoulder_abduction',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Adjust the seat so the pads sit just above your elbows.',
      'Raise your arms to shoulder height.',
      'Lower with a slow negative.',
    ],
    commonMistakes: ['Rushing the negative.'],
    scienceExplanation:
      'The fixed path makes momentum impossible, so every rep keeps tension on the side delts.',
    progressionInstructions: 'One pin at a time after topping the range.',
    equivalentAlternatives: ['lateral-raise', 'cable-lateral-raise'],
  }),
  defineExercise({
    slug: 'band-lateral-raise',
    name: 'Band Lateral Raise',
    description: 'Side raise against a band for home training.',
    primaryMuscles: ['shoulders'],
    equipment: ['resistance_band'],
    movementPattern: 'shoulder_abduction',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Stand on the band, handles at your sides.',
      'Raise out to shoulder height, pause briefly.',
      'Lower with control.',
    ],
    commonMistakes: ['Letting the band snap the arms down.'],
    scienceExplanation:
      'Band tension peaks at the top where the delts work hardest in abduction, a decent match for this movement.',
    progressionInstructions: 'Add reps, widen your stance, or use a thicker band.',
    equivalentAlternatives: ['lateral-raise'],
  }),
  defineExercise({
    slug: 'reverse-fly',
    name: 'Reverse Dumbbell Fly',
    aliases: ['Rear Delt Fly'],
    description: 'Hinged dumbbell fly targeting the rear delts and upper back.',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back'],
    equipment: ['dumbbell'],
    movementPattern: 'rear_delt',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    instructions: [
      'Hinge forward with a flat back, dumbbells hanging below your chest.',
      'Raise your arms out wide, leading with the pinkies.',
      'Lower slowly without swinging.',
    ],
    commonMistakes: ['Standing too upright.', 'Squeezing the blades so the traps take over.'],
    scienceExplanation:
      'Rear delts get little direct work from presses; targeting them balances shoulder development and pressing posture.',
    progressionInstructions: 'High reps, small load steps; strictness first.',
    equivalentAlternatives: ['face-pull', 'band-pull-apart'],
  }),
  defineExercise({
    slug: 'band-pull-apart',
    name: 'Band Pull-Apart',
    description: 'Horizontal band pull for rear delts and scapular muscles.',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back'],
    equipment: ['resistance_band'],
    movementPattern: 'rear_delt',
    difficulty: 'beginner',
    exerciseType: 'isolation',
    trackingType: 'bodyweight_reps',
    instructions: [
      'Hold a band at shoulder height, hands shoulder-width.',
      'Pull the band apart until it touches your chest.',
      'Return slowly, keeping tension.',
    ],
    commonMistakes: ['Dropping the arms as they fatigue.'],
    scienceExplanation:
      'Cheap, joint-friendly volume for the small posterior shoulder muscles that heavy pressing programs tend to underfeed.',
    progressionInstructions: 'Add reps, choke up on the band, or use a thicker band.',
    equivalentAlternatives: ['face-pull', 'reverse-fly'],
  }),
] as const;
